services:
  todoist-habitica-sync:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.12.4
    image: todoist-habitica-sync:local
    container_name: todoist-habitica-sync
    env_file:
      - .env
    volumes:
    - ./.sync_cache:/app/.sync_cache
    restart: always
