version: '3.8'
services:
  todoist-habitica-sync:
    image: "radeklat/todoist-habitica-sync:1.1.1"
    container_name: todoist-habitica-sync
    env_file:
      - .env
    volumes:
    - ./.sync_cache:/usr/src/app/.sync_cache
    restart: always
