version: '3.8'
services:
  todoist-habitica-sync:
    image: "radeklat/todoist-habitica-sync:latest"
    container_name: todoist-habitica-sync
    env_file:
      - .env
    volumes:
      - ./src:/app/src
#    - ./.sync_cache:/app/.sync_cache
    restart: always
